name: For Your Glory
favicon: null
layout_spectrum: 0.49123
typography_spectrum: 0.07239
title: 'For Your Glory: A Prophetic Movement'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006fcb'
    - '#030305'
    - '#e4dbd6'
    - '#4cbaf5'
    - '#36425c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
